# Generated by Django 3.1.4 on 2021-01-03 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('carname', models.ManyToManyField(to='carsapi.Car')),
            ],
        ),
    ]
